server:
  port: 9001

spring:
  application:
    name: codeworld-cloud-goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/codeworld-cloud-shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
        weight: 1
  redis:
    database: 3
    host: 192.168.2.4
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
codeworld:
  jwt:
    secret: codeworld@Login(Auth}*^31)&codeworld% # 用于生存rsa公钥和私钥的密文,越复杂越好
    pubKeyPath: D:\\temp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: D:\\temp\\rsa\\rsa.pri # 私钥地址
    expire: 30   # 过期时间,单位分钟
    cookieMaxAge: 1800
    cookieName: token

logging:
  config: classpath:log/logback-spring.xml
  level:
    com.codeworld.fc.goods.product.mapper: debug

xxl:
  job:
    accessToken:
    admin:
      addresses: http://localhost:9999/xxl-job-admin
    executor:
      address:
      appname: xxl-job-product
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9002

#ribbon:
#  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒
#  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
#  MaxAutoRetries: 1 #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
#feign:
#  hystrix:
#    enabled: true
